In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
sns.set_style('darkgrid')
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [2]:
data = pd.read_csv('iris.csv',names=['sep_l','sep_w','pet_l','pet_w','label'])

In [3]:
data

sep_l  sep_w  pet_l  pet_w           label
0      5.1    3.5    1.4    0.2     Iris-setosa
1      4.9    3.0    1.4    0.2     Iris-setosa
2      4.7    3.2    1.3    0.2     Iris-setosa
3      4.6    3.1    1.5    0.2     Iris-setosa
4      5.0    3.6    1.4    0.2     Iris-setosa
..     ...    ...    ...    ...             ...
145    6.7    3.0    5.2    2.3  Iris-virginica
146    6.3    2.5    5.0    1.9  Iris-virginica
147    6.5    3.0    5.2    2.0  Iris-virginica
148    6.2    3.4    5.4    2.3  Iris-virginica
149    5.9    3.0    5.1    1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
le = LabelEncoder()

In [6]:
data['label'] = le.fit_transform(data['label'])

In [7]:
data 

sep_l  sep_w  pet_l  pet_w  label
0      5.1    3.5    1.4    0.2      0
1      4.9    3.0    1.4    0.2      0
2      4.7    3.2    1.3    0.2      0
3      4.6    3.1    1.5    0.2      0
4      5.0    3.6    1.4    0.2      0
..     ...    ...    ...    ...    ...
145    6.7    3.0    5.2    2.3      2
146    6.3    2.5    5.0    1.9      2
147    6.5    3.0    5.2    2.0      2
148    6.2    3.4    5.4    2.3      2
149    5.9    3.0    5.1    1.8      2

[150 rows x 5 columns]

In [8]:
x = data.iloc[:,0:4].values

In [9]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
y = data.iloc[:,4].values

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
model = SVC()

In [13]:
from sklearn.model_selection import cross_val_score

In [14]:
accuracy = cross_val_score(model,x,y,scoring='accuracy',cv=10)

In [15]:
accuracy

array([1.        , 0.93333333, 1.        , 1.        , 1.        ,
       0.93333333, 0.93333333, 0.93333333, 1.        , 1.        ])

In [16]:
accuracy.mean()

0.9733333333333334